export type CageOp = '+' | '-' | '*' | '/' | 'given'

export interface Cage {
  cells: [number, number][]
  target: number
  op: CageOp
}

export interface MurdokuPuzzle {
  id: number
  size: number
  name: string
  subtitle: string
  cages: Cage[]
  solution: number[][]
}

export const MURDOKU_PUZZLES: MurdokuPuzzle[] = [
  {
    id: 1,
    size: 4,
    name: 'The Attic',
    subtitle: '4×4 · Beginner',
    solution: [
      [1, 2, 3, 4],
      [2, 1, 4, 3],
      [3, 4, 1, 2],
      [4, 3, 2, 1],
    ],
    cages: [
      { cells: [[0,0],[1,0]], target: 3,  op: '+' },
      { cells: [[0,1],[0,2]], target: 5,  op: '+' },
      { cells: [[0,3],[1,3]], target: 7,  op: '+' },
      { cells: [[1,1],[1,2]], target: 5,  op: '+' },
      { cells: [[2,0],[2,1],[2,2]], target: 8, op: '+' },
      { cells: [[2,3],[3,3]], target: 3,  op: '+' },
      { cells: [[3,0],[3,1]], target: 7,  op: '+' },
      { cells: [[3,2]], target: 2, op: 'given' },
    ],
  },
  {
    id: 2,
    size: 4,
    name: 'The Cellar',
    subtitle: '4×4 · Easy',
    solution: [
      [1, 2, 3, 4],
      [3, 4, 1, 2],
      [2, 1, 4, 3],
      [4, 3, 2, 1],
    ],
    cages: [
      { cells: [[0,0],[0,1]], target: 3,  op: '+' },
      { cells: [[0,2],[1,2]], target: 4,  op: '+' },
      { cells: [[0,3],[1,3]], target: 6,  op: '+' },
      { cells: [[1,0],[2,0]], target: 5,  op: '+' },
      { cells: [[1,1],[2,1]], target: 5,  op: '+' },
      { cells: [[2,2],[3,2]], target: 6,  op: '+' },
      { cells: [[2,3],[3,3]], target: 4,  op: '+' },
      { cells: [[3,0],[3,1]], target: 7,  op: '+' },
    ],
  },
  {
    id: 3,
    size: 4,
    name: 'The Kitchen',
    subtitle: '4×4 · Medium · with ×',
    solution: [
      [3, 4, 1, 2],
      [1, 2, 4, 3],
      [4, 3, 2, 1],
      [2, 1, 3, 4],
    ],
    cages: [
      { cells: [[0,0],[0,1]], target: 12, op: '*' },
      { cells: [[0,2],[0,3]], target: 3,  op: '+' },
      { cells: [[1,0],[1,1]], target: 3,  op: '+' },
      { cells: [[1,2],[1,3]], target: 7,  op: '+' },
      { cells: [[2,0],[3,0]], target: 6,  op: '+' },
      { cells: [[2,1],[3,1]], target: 4,  op: '+' },
      { cells: [[2,2],[2,3]], target: 3,  op: '+' },
      { cells: [[3,2],[3,3]], target: 7,  op: '+' },
    ],
  },
  {
    id: 4,
    size: 5,
    name: 'The Library',
    subtitle: '5×5 · Easy',
    solution: [
      [1, 2, 3, 4, 5],
      [2, 3, 4, 5, 1],
      [3, 4, 5, 1, 2],
      [4, 5, 1, 2, 3],
      [5, 1, 2, 3, 4],
    ],
    cages: [
      { cells: [[0,0]], target: 1, op: 'given' },
      { cells: [[0,1],[0,2]], target: 5,  op: '+' },
      { cells: [[0,3],[0,4]], target: 9,  op: '+' },
      { cells: [[1,0],[2,0]], target: 5,  op: '+' },
      { cells: [[1,1],[2,1]], target: 7,  op: '+' },
      { cells: [[1,2],[2,2]], target: 9,  op: '+' },
      { cells: [[1,3],[2,3]], target: 6,  op: '+' },
      { cells: [[1,4],[2,4]], target: 3,  op: '+' },
      { cells: [[3,0],[4,0]], target: 9,  op: '+' },
      { cells: [[3,1],[4,1]], target: 6,  op: '+' },
      { cells: [[3,2],[4,2]], target: 3,  op: '+' },
      { cells: [[3,3],[4,3]], target: 5,  op: '+' },
      { cells: [[3,4],[4,4]], target: 7,  op: '+' },
    ],
  },
  {
    id: 5,
    size: 5,
    name: 'The Study',
    subtitle: '5×5 · Medium',
    solution: [
      [1, 3, 5, 2, 4],
      [2, 4, 1, 3, 5],
      [3, 5, 2, 4, 1],
      [4, 1, 3, 5, 2],
      [5, 2, 4, 1, 3],
    ],
    cages: [
      { cells: [[0,0],[0,1]], target: 4,  op: '+' },
      { cells: [[0,2],[0,3]], target: 7,  op: '+' },
      { cells: [[0,4],[1,4],[2,4]], target: 10, op: '+' },
      { cells: [[1,0],[2,0]], target: 5,  op: '+' },
      { cells: [[1,1],[2,1]], target: 9,  op: '+' },
      { cells: [[1,2],[2,2]], target: 3,  op: '+' },
      { cells: [[1,3],[2,3]], target: 7,  op: '+' },
      { cells: [[3,0],[4,0]], target: 9,  op: '+' },
      { cells: [[3,1],[4,1]], target: 3,  op: '+' },
      { cells: [[3,2],[4,2]], target: 7,  op: '+' },
      { cells: [[3,3],[4,3]], target: 6,  op: '+' },
      { cells: [[3,4],[4,4]], target: 5,  op: '+' },
    ],
  },
  {
    id: 6,
    size: 5,
    name: 'The Garden',
    subtitle: '5×5 · Medium-Hard',
    solution: [
      [2, 5, 4, 1, 3],
      [4, 3, 1, 5, 2],
      [1, 2, 5, 3, 4],
      [5, 4, 3, 2, 1],
      [3, 1, 2, 4, 5],
    ],
    cages: [
      { cells: [[0,0],[1,0]], target: 6,  op: '+' },
      { cells: [[0,1],[1,1]], target: 8,  op: '+' },
      { cells: [[0,2],[1,2]], target: 5,  op: '+' },
      { cells: [[0,3],[1,3]], target: 6,  op: '+' },
      { cells: [[0,4],[1,4]], target: 5,  op: '+' },
      { cells: [[2,0],[2,1]], target: 3,  op: '+' },
      { cells: [[2,2],[3,2]], target: 8,  op: '+' },
      { cells: [[2,3],[3,3]], target: 5,  op: '+' },
      { cells: [[2,4],[3,4]], target: 5,  op: '+' },
      { cells: [[3,0],[4,0]], target: 8,  op: '+' },
      { cells: [[3,1],[4,1]], target: 5,  op: '+' },
      { cells: [[4,2],[4,3]], target: 6,  op: '+' },
      { cells: [[4,4]], target: 5, op: 'given' },
    ],
  },
  {
    id: 7,
    size: 6,
    name: 'The Ballroom',
    subtitle: '6×6 · Medium',
    solution: [
      [1, 2, 3, 4, 5, 6],
      [2, 3, 4, 5, 6, 1],
      [3, 4, 5, 6, 1, 2],
      [4, 5, 6, 1, 2, 3],
      [5, 6, 1, 2, 3, 4],
      [6, 1, 2, 3, 4, 5],
    ],
    cages: [
      { cells: [[0,0],[0,1]], target: 3,  op: '+' },
      { cells: [[0,2],[0,3]], target: 7,  op: '+' },
      { cells: [[0,4],[0,5]], target: 11, op: '+' },
      { cells: [[1,0],[1,1]], target: 5,  op: '+' },
      { cells: [[1,2],[1,3]], target: 9,  op: '+' },
      { cells: [[1,4],[1,5]], target: 7,  op: '+' },
      { cells: [[2,0],[3,0]], target: 7,  op: '+' },
      { cells: [[2,1],[3,1]], target: 9,  op: '+' },
      { cells: [[2,2],[3,2]], target: 11, op: '+' },
      { cells: [[2,3],[3,3]], target: 7,  op: '+' },
      { cells: [[2,4],[3,4]], target: 3,  op: '+' },
      { cells: [[2,5],[3,5]], target: 5,  op: '+' },
      { cells: [[4,0],[5,0]], target: 11, op: '+' },
      { cells: [[4,1],[5,1]], target: 7,  op: '+' },
      { cells: [[4,2],[5,2]], target: 3,  op: '+' },
      { cells: [[4,3],[5,3]], target: 5,  op: '+' },
      { cells: [[4,4],[5,4]], target: 7,  op: '+' },
      { cells: [[4,5],[5,5]], target: 9,  op: '+' },
    ],
  },
  {
    id: 8,
    size: 6,
    name: 'The Trophy Room',
    subtitle: '6×6 · Hard',
    solution: [
      [1, 5, 3, 2, 6, 4],
      [4, 2, 6, 5, 3, 1],
      [2, 6, 1, 4, 5, 3],
      [6, 4, 5, 3, 1, 2],
      [3, 1, 4, 6, 2, 5],
      [5, 3, 2, 1, 4, 6],
    ],
    cages: [
      { cells: [[0,0],[1,0]], target: 5,  op: '+' },
      { cells: [[0,1],[0,2]], target: 8,  op: '+' },
      { cells: [[0,3],[0,4]], target: 8,  op: '+' },
      { cells: [[0,5],[1,5]], target: 5,  op: '+' },
      { cells: [[1,1],[2,1]], target: 8,  op: '+' },
      { cells: [[1,2],[2,2]], target: 7,  op: '+' },
      { cells: [[1,3],[2,3]], target: 9,  op: '+' },
      { cells: [[1,4],[2,4]], target: 8,  op: '+' },
      { cells: [[2,0],[3,0]], target: 8,  op: '+' },
      { cells: [[2,5],[3,5]], target: 5,  op: '+' },
      { cells: [[3,1],[4,1]], target: 5,  op: '+' },
      { cells: [[3,2],[4,2]], target: 9,  op: '+' },
      { cells: [[3,3],[4,3]], target: 9,  op: '+' },
      { cells: [[3,4],[4,4]], target: 3,  op: '+' },
      { cells: [[4,0],[5,0]], target: 8,  op: '+' },
      { cells: [[5,1],[5,2]], target: 5,  op: '+' },
      { cells: [[5,3],[5,4]], target: 5,  op: '+' },
      { cells: [[4,5],[5,5]], target: 11, op: '+' },
    ],
  },
  {
    id: 9,
    size: 6,
    name: 'The Vault',
    subtitle: '6×6 · Harder',
    solution: [
      [2, 4, 6, 1, 3, 5],
      [5, 1, 3, 6, 4, 2],
      [6, 3, 5, 2, 1, 4],
      [1, 6, 4, 5, 2, 3],
      [4, 2, 1, 3, 5, 6],
      [3, 5, 2, 4, 6, 1],
    ],
    cages: [
      { cells: [[0,0],[1,0]], target: 7,  op: '+' },
      { cells: [[0,1],[1,1]], target: 5,  op: '+' },
      { cells: [[0,2],[1,2]], target: 9,  op: '+' },
      { cells: [[0,3],[1,3]], target: 7,  op: '+' },
      { cells: [[0,4],[0,5]], target: 8,  op: '+' },
      { cells: [[1,4],[1,5]], target: 6,  op: '+' },
      { cells: [[2,0],[2,1]], target: 9,  op: '+' },
      { cells: [[2,2],[2,3]], target: 7,  op: '+' },
      { cells: [[2,4],[3,4]], target: 3,  op: '+' },
      { cells: [[2,5],[3,5]], target: 7,  op: '+' },
      { cells: [[3,0],[3,1]], target: 7,  op: '+' },
      { cells: [[3,2],[4,2]], target: 5,  op: '+' },
      { cells: [[3,3],[4,3]], target: 8,  op: '+' },
      { cells: [[4,0],[5,0]], target: 7,  op: '+' },
      { cells: [[4,1],[5,1]], target: 7,  op: '+' },
      { cells: [[4,4],[4,5]], target: 11, op: '+' },
      { cells: [[5,2],[5,3]], target: 6,  op: '+' },
      { cells: [[5,4],[5,5]], target: 7,  op: '+' },
    ],
  },
  {
    id: 10,
    size: 6,
    name: 'The Conservatory',
    subtitle: '6×6 · Hardest',
    solution: [
      [5, 2, 4, 6, 1, 3],
      [3, 6, 1, 2, 5, 4],
      [6, 1, 5, 4, 3, 2],
      [2, 4, 3, 1, 6, 5],
      [4, 5, 6, 3, 2, 1],
      [1, 3, 2, 5, 4, 6],
    ],
    cages: [
      { cells: [[0,0],[0,1],[1,1]], target: 13, op: '+' },
      { cells: [[0,2],[0,3]], target: 10, op: '+' },
      { cells: [[0,4],[0,5]], target: 4,  op: '+' },
      { cells: [[1,0],[2,0]], target: 9,  op: '+' },
      { cells: [[1,2],[2,2]], target: 6,  op: '+' },
      { cells: [[1,3],[1,4]], target: 7,  op: '+' },
      { cells: [[1,5],[2,5]], target: 6,  op: '+' },
      { cells: [[2,1],[3,1]], target: 5,  op: '+' },
      { cells: [[2,3],[2,4]], target: 7,  op: '+' },
      { cells: [[3,0],[4,0]], target: 6,  op: '+' },
      { cells: [[3,2],[4,2]], target: 9,  op: '+' },
      { cells: [[3,3],[4,3]], target: 4,  op: '+' },
      { cells: [[3,4],[3,5]], target: 11, op: '+' },
      { cells: [[4,1],[5,1]], target: 8,  op: '+' },
      { cells: [[4,4],[4,5]], target: 3,  op: '+' },
      { cells: [[5,0]], target: 1, op: 'given' },
      { cells: [[5,2],[5,3]], target: 7,  op: '+' },
      { cells: [[5,4],[5,5]], target: 10, op: '+' },
    ],
  },
]
